# Item required to use a warp sign
use-item: ENDER_PEARL

# Number of items consumed by using a warp sign
use-cost: 1

# Sound played when teleporting
teleport-sound: ENTITY_ENDERMAN_TELEPORT

# Effect displayed when teleporting
teleport-effect: ENDER_SIGNAL

# Custom messages
messages:
  create_permission: "&cYou do not have the required permissions to create warp signs!"
  no_warp_name: "&cNo warp name set!\nPlease specify the warp name on the second line."
  warp_created: "&aWarp sign successfully placed."
  warp_name_taken: "&cA warp target with the same name already exists!"
  warp_destroyed: "&aWarp destroyed."
  target_sign_created: "&aTarget sign for warp successfully placed."
  destroy_permission: "&cYou do not have the required permissions to destroy warp signs!"
  invalid_item: "&cYou must use {use-item} for this warp!"
  not_enough_item: "&cYou need {use-cost} {use-item} for this warp!"
  warp_not_found: "&cSpecified warp does not exist!"
  use_permission: "&cYou do not have the required permissions to use the warp sign!"
  teleport: "&eTeleporting to {warp-name}..."
  not_permission: "&cYou do not have permission!"